name: Test Feature Branch

on:
  pull_request:
    branches: [develop]

jobs:
  test:
    name: Test Feature Branch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout Feature Branch
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Creating Neo4j Container
        run: |
          chmod +x ./scripts/docker-neo4j-initializer/docker-neo4j.sh
          ./scripts/docker-neo4j-initializer/docker-neo4j.sh
          sleep 30s
          chmod +x ./scripts/docker-neo4j-initializer/start-movies-db.sh
          ./scripts/docker-neo4j-initializer/start-movies-db.sh
      - run: yarn install
      - name: Quality Gate 1 of 2 - Eslint check
        run: yarn run lint
      - name: Quality Gate 2 of 2 - Cypress Tests
        uses: cypress-io/github-action@v4
        with:
          build: yarn run build
          start: yarn run dev
          wait-on: 'http://localhost:3000'
          browser: chrome
