name: Test/Deploy Develop

on:
  push:
    branches: [develop]

jobs:
  deploy-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: neodash-mbenz
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/neodash-mbenz.tar
          docker image ls -a
      - name: 'Azure ACR Login'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Push Image
        run: |
          docker push updatepath.azurecr.io/neodash-mbenz
